version: '3.4'

services:
  rockstor:
    image: psykar/rockstor:latest
    privileged: true
    # hostname: rockstor
    # network_mode: host
    tmpfs: /run
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
